import { z } from "zod";
export declare const ApprovalStatusSchema: z.ZodEnum<["pending", "approved", "rejected", "timed_out", "auto_approved", "cancelled"]>;
export type ApprovalStatus = z.infer<typeof ApprovalStatusSchema>;
export declare const ApprovalDecisionTypeSchema: z.ZodEnum<["APPROVED", "REJECTED"]>;
export type ApprovalDecisionType = z.infer<typeof ApprovalDecisionTypeSchema>;
export declare const ToolApprovalRequestSchema: z.ZodObject<{
    id: z.ZodString;
    tenantId: z.ZodString;
    sessionId: z.ZodString;
    agentId: z.ZodString;
    taskId: z.ZodOptional<z.ZodString>;
    workspaceId: z.ZodOptional<z.ZodString>;
    clineSessionId: z.ZodString;
    callId: z.ZodString;
    toolName: z.ZodString;
    toolParameters: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    riskLevel: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>>;
    reason: z.ZodOptional<z.ZodString>;
    status: z.ZodDefault<z.ZodEnum<["pending", "approved", "rejected", "timed_out", "auto_approved", "cancelled"]>>;
    timeoutSeconds: z.ZodDefault<z.ZodNumber>;
    expiresAt: z.ZodString;
    createdAt: z.ZodDefault<z.ZodString>;
    resolvedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "timed_out" | "cancelled" | "pending" | "approved" | "rejected" | "auto_approved";
    riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    id: string;
    tenantId: string;
    createdAt: string;
    timeoutSeconds: number;
    agentId: string;
    clineSessionId: string;
    sessionId: string;
    callId: string;
    toolName: string;
    toolParameters: Record<string, unknown>;
    expiresAt: string;
    taskId?: string | undefined;
    workspaceId?: string | undefined;
    reason?: string | undefined;
    resolvedAt?: string | undefined;
}, {
    id: string;
    tenantId: string;
    agentId: string;
    clineSessionId: string;
    sessionId: string;
    callId: string;
    toolName: string;
    expiresAt: string;
    status?: "timed_out" | "cancelled" | "pending" | "approved" | "rejected" | "auto_approved" | undefined;
    riskLevel?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | undefined;
    createdAt?: string | undefined;
    timeoutSeconds?: number | undefined;
    taskId?: string | undefined;
    workspaceId?: string | undefined;
    reason?: string | undefined;
    toolParameters?: Record<string, unknown> | undefined;
    resolvedAt?: string | undefined;
}>;
export type ToolApprovalRequest = z.infer<typeof ToolApprovalRequestSchema>;
export declare const ApprovalDecisionSchema: z.ZodObject<{
    requestId: z.ZodString;
    tenantId: z.ZodString;
    decision: z.ZodEnum<["APPROVED", "REJECTED"]>;
    decidedByUserId: z.ZodOptional<z.ZodString>;
    decidedByRole: z.ZodOptional<z.ZodString>;
    reason: z.ZodOptional<z.ZodString>;
    modifiedParameters: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    decidedAt: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    tenantId: string;
    decision: "APPROVED" | "REJECTED";
    requestId: string;
    decidedAt: string;
    reason?: string | undefined;
    decidedByUserId?: string | undefined;
    decidedByRole?: string | undefined;
    modifiedParameters?: Record<string, unknown> | undefined;
}, {
    tenantId: string;
    decision: "APPROVED" | "REJECTED";
    requestId: string;
    reason?: string | undefined;
    decidedByUserId?: string | undefined;
    decidedByRole?: string | undefined;
    modifiedParameters?: Record<string, unknown> | undefined;
    decidedAt?: string | undefined;
}>;
export type ApprovalDecision = z.infer<typeof ApprovalDecisionSchema>;
export declare const ApprovalResolutionSchema: z.ZodObject<{
    requestId: z.ZodString;
    status: z.ZodEnum<["pending", "approved", "rejected", "timed_out", "auto_approved", "cancelled"]>;
    decision: z.ZodOptional<z.ZodObject<{
        requestId: z.ZodString;
        tenantId: z.ZodString;
        decision: z.ZodEnum<["APPROVED", "REJECTED"]>;
        decidedByUserId: z.ZodOptional<z.ZodString>;
        decidedByRole: z.ZodOptional<z.ZodString>;
        reason: z.ZodOptional<z.ZodString>;
        modifiedParameters: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        decidedAt: z.ZodDefault<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        tenantId: string;
        decision: "APPROVED" | "REJECTED";
        requestId: string;
        decidedAt: string;
        reason?: string | undefined;
        decidedByUserId?: string | undefined;
        decidedByRole?: string | undefined;
        modifiedParameters?: Record<string, unknown> | undefined;
    }, {
        tenantId: string;
        decision: "APPROVED" | "REJECTED";
        requestId: string;
        reason?: string | undefined;
        decidedByUserId?: string | undefined;
        decidedByRole?: string | undefined;
        modifiedParameters?: Record<string, unknown> | undefined;
        decidedAt?: string | undefined;
    }>>;
    approvedParameters: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    resolvedAt: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "timed_out" | "cancelled" | "pending" | "approved" | "rejected" | "auto_approved";
    resolvedAt: string;
    requestId: string;
    decision?: {
        tenantId: string;
        decision: "APPROVED" | "REJECTED";
        requestId: string;
        decidedAt: string;
        reason?: string | undefined;
        decidedByUserId?: string | undefined;
        decidedByRole?: string | undefined;
        modifiedParameters?: Record<string, unknown> | undefined;
    } | undefined;
    approvedParameters?: Record<string, unknown> | undefined;
}, {
    status: "timed_out" | "cancelled" | "pending" | "approved" | "rejected" | "auto_approved";
    requestId: string;
    decision?: {
        tenantId: string;
        decision: "APPROVED" | "REJECTED";
        requestId: string;
        reason?: string | undefined;
        decidedByUserId?: string | undefined;
        decidedByRole?: string | undefined;
        modifiedParameters?: Record<string, unknown> | undefined;
        decidedAt?: string | undefined;
    } | undefined;
    resolvedAt?: string | undefined;
    approvedParameters?: Record<string, unknown> | undefined;
}>;
export type ApprovalResolution = z.infer<typeof ApprovalResolutionSchema>;
export declare const CreateApprovalRequestSchema: z.ZodObject<{
    tenantId: z.ZodString;
    sessionId: z.ZodString;
    agentId: z.ZodString;
    taskId: z.ZodOptional<z.ZodString>;
    workspaceId: z.ZodOptional<z.ZodString>;
    clineSessionId: z.ZodString;
    callId: z.ZodString;
    toolName: z.ZodString;
    toolParameters: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    riskLevel: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>>;
    reason: z.ZodOptional<z.ZodString>;
    timeoutSeconds: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    tenantId: string;
    timeoutSeconds: number;
    agentId: string;
    clineSessionId: string;
    sessionId: string;
    callId: string;
    toolName: string;
    toolParameters: Record<string, unknown>;
    taskId?: string | undefined;
    workspaceId?: string | undefined;
    reason?: string | undefined;
}, {
    tenantId: string;
    agentId: string;
    clineSessionId: string;
    sessionId: string;
    callId: string;
    toolName: string;
    riskLevel?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | undefined;
    timeoutSeconds?: number | undefined;
    taskId?: string | undefined;
    workspaceId?: string | undefined;
    reason?: string | undefined;
    toolParameters?: Record<string, unknown> | undefined;
}>;
export type CreateApprovalRequest = z.infer<typeof CreateApprovalRequestSchema>;
//# sourceMappingURL=approval.d.ts.map