import { z } from "zod";
export declare const SynapseEventTypeSchema: z.ZodEnum<["agent.created", "agent.updated", "agent.deleted", "agent.status_changed", "agent.started", "agent.paused", "agent.resumed", "agent.stopped", "agent.aborted", "agent.failed", "session.initialized", "session.started", "session.chunk", "session.message", "session.thought", "session.paused", "session.resumed", "session.checkpoint_created", "session.checkpoint_restored", "session.ended", "task.created", "task.scheduled", "task.dispatched", "task.status_changed", "task.started", "task.completed", "task.failed", "task.retry", "task.cancelled", "tool.requested", "tool.policy_checked", "tool.approval_required", "tool.approved", "tool.rejected", "tool.executed", "tool.failed", "policy.evaluated", "policy.allowed", "policy.blocked", "policy.violation", "governance.kill_switch_triggered", "verification.plan_created", "verification.started", "verification.assertion_passed", "verification.assertion_failed", "verification.completed", "evidence.collected", "evidence.sealed", "team.created", "team.member_joined", "team.member_left", "team.progress_updated", "team.delegation_started", "team.delegation_completed", "workspace.provisioned", "workspace.modified", "workspace.locked", "workspace.unlocked", "workspace.snapshot_created", "world.entity_mutated", "world.snapshot_captured", "simulation.started", "simulation.tick", "simulation.diff_generated", "simulation.completed", "audit.entry_recorded", "telemetry.metric_emitted", "system.heartbeat", "system.error"]>;
export type SynapseEventType = z.infer<typeof SynapseEventTypeSchema>;
export declare const SynapseEventSourceSchema: z.ZodEnum<["engine.cline", "engine.adapter", "control.plane", "api", "verifier", "simulator", "scheduler", "policy.engine", "realtime.hub"]>;
export type SynapseEventSource = z.infer<typeof SynapseEventSourceSchema>;
export declare const SynapseEventEnvelopeSchema: z.ZodObject<{
    eventId: z.ZodString;
    eventType: z.ZodEnum<["agent.created", "agent.updated", "agent.deleted", "agent.status_changed", "agent.started", "agent.paused", "agent.resumed", "agent.stopped", "agent.aborted", "agent.failed", "session.initialized", "session.started", "session.chunk", "session.message", "session.thought", "session.paused", "session.resumed", "session.checkpoint_created", "session.checkpoint_restored", "session.ended", "task.created", "task.scheduled", "task.dispatched", "task.status_changed", "task.started", "task.completed", "task.failed", "task.retry", "task.cancelled", "tool.requested", "tool.policy_checked", "tool.approval_required", "tool.approved", "tool.rejected", "tool.executed", "tool.failed", "policy.evaluated", "policy.allowed", "policy.blocked", "policy.violation", "governance.kill_switch_triggered", "verification.plan_created", "verification.started", "verification.assertion_passed", "verification.assertion_failed", "verification.completed", "evidence.collected", "evidence.sealed", "team.created", "team.member_joined", "team.member_left", "team.progress_updated", "team.delegation_started", "team.delegation_completed", "workspace.provisioned", "workspace.modified", "workspace.locked", "workspace.unlocked", "workspace.snapshot_created", "world.entity_mutated", "world.snapshot_captured", "simulation.started", "simulation.tick", "simulation.diff_generated", "simulation.completed", "audit.entry_recorded", "telemetry.metric_emitted", "system.heartbeat", "system.error"]>;
    tenantId: z.ZodString;
    agentId: z.ZodOptional<z.ZodString>;
    sessionId: z.ZodOptional<z.ZodString>;
    taskId: z.ZodOptional<z.ZodString>;
    workspaceId: z.ZodOptional<z.ZodString>;
    runtimeId: z.ZodOptional<z.ZodString>;
    timestamp: z.ZodDefault<z.ZodNumber>;
    isoTimestamp: z.ZodDefault<z.ZodString>;
    sequence: z.ZodNumber;
    source: z.ZodEnum<["engine.cline", "engine.adapter", "control.plane", "api", "verifier", "simulator", "scheduler", "policy.engine", "realtime.hub"]>;
    payload: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    traceId: z.ZodDefault<z.ZodString>;
    parentEventId: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    tenantId: string;
    eventId: string;
    eventType: "agent.created" | "agent.updated" | "agent.deleted" | "agent.status_changed" | "agent.started" | "agent.paused" | "agent.resumed" | "agent.stopped" | "agent.aborted" | "agent.failed" | "session.initialized" | "session.started" | "session.chunk" | "session.message" | "session.thought" | "session.paused" | "session.resumed" | "session.checkpoint_created" | "session.checkpoint_restored" | "session.ended" | "task.created" | "task.scheduled" | "task.dispatched" | "task.status_changed" | "task.started" | "task.completed" | "task.failed" | "task.retry" | "task.cancelled" | "tool.requested" | "tool.policy_checked" | "tool.approval_required" | "tool.approved" | "tool.rejected" | "tool.executed" | "tool.failed" | "policy.evaluated" | "policy.allowed" | "policy.blocked" | "policy.violation" | "governance.kill_switch_triggered" | "verification.plan_created" | "verification.started" | "verification.assertion_passed" | "verification.assertion_failed" | "verification.completed" | "evidence.collected" | "evidence.sealed" | "team.created" | "team.member_joined" | "team.member_left" | "team.progress_updated" | "team.delegation_started" | "team.delegation_completed" | "workspace.provisioned" | "workspace.modified" | "workspace.locked" | "workspace.unlocked" | "workspace.snapshot_created" | "world.entity_mutated" | "world.snapshot_captured" | "simulation.started" | "simulation.tick" | "simulation.diff_generated" | "simulation.completed" | "audit.entry_recorded" | "telemetry.metric_emitted" | "system.heartbeat" | "system.error";
    timestamp: number;
    isoTimestamp: string;
    sequence: number;
    source: "engine.cline" | "engine.adapter" | "control.plane" | "api" | "verifier" | "simulator" | "scheduler" | "policy.engine" | "realtime.hub";
    payload: Record<string, unknown>;
    traceId: string;
    runtimeId?: string | undefined;
    agentId?: string | undefined;
    taskId?: string | undefined;
    workspaceId?: string | undefined;
    sessionId?: string | undefined;
    parentEventId?: string | undefined;
}, {
    tenantId: string;
    eventId: string;
    eventType: "agent.created" | "agent.updated" | "agent.deleted" | "agent.status_changed" | "agent.started" | "agent.paused" | "agent.resumed" | "agent.stopped" | "agent.aborted" | "agent.failed" | "session.initialized" | "session.started" | "session.chunk" | "session.message" | "session.thought" | "session.paused" | "session.resumed" | "session.checkpoint_created" | "session.checkpoint_restored" | "session.ended" | "task.created" | "task.scheduled" | "task.dispatched" | "task.status_changed" | "task.started" | "task.completed" | "task.failed" | "task.retry" | "task.cancelled" | "tool.requested" | "tool.policy_checked" | "tool.approval_required" | "tool.approved" | "tool.rejected" | "tool.executed" | "tool.failed" | "policy.evaluated" | "policy.allowed" | "policy.blocked" | "policy.violation" | "governance.kill_switch_triggered" | "verification.plan_created" | "verification.started" | "verification.assertion_passed" | "verification.assertion_failed" | "verification.completed" | "evidence.collected" | "evidence.sealed" | "team.created" | "team.member_joined" | "team.member_left" | "team.progress_updated" | "team.delegation_started" | "team.delegation_completed" | "workspace.provisioned" | "workspace.modified" | "workspace.locked" | "workspace.unlocked" | "workspace.snapshot_created" | "world.entity_mutated" | "world.snapshot_captured" | "simulation.started" | "simulation.tick" | "simulation.diff_generated" | "simulation.completed" | "audit.entry_recorded" | "telemetry.metric_emitted" | "system.heartbeat" | "system.error";
    sequence: number;
    source: "engine.cline" | "engine.adapter" | "control.plane" | "api" | "verifier" | "simulator" | "scheduler" | "policy.engine" | "realtime.hub";
    runtimeId?: string | undefined;
    agentId?: string | undefined;
    taskId?: string | undefined;
    workspaceId?: string | undefined;
    sessionId?: string | undefined;
    timestamp?: number | undefined;
    isoTimestamp?: string | undefined;
    payload?: Record<string, unknown> | undefined;
    traceId?: string | undefined;
    parentEventId?: string | undefined;
}>;
export type SynapseEventEnvelope = z.infer<typeof SynapseEventEnvelopeSchema>;
export declare const CreateEventInputSchema: z.ZodObject<Omit<{
    eventId: z.ZodString;
    eventType: z.ZodEnum<["agent.created", "agent.updated", "agent.deleted", "agent.status_changed", "agent.started", "agent.paused", "agent.resumed", "agent.stopped", "agent.aborted", "agent.failed", "session.initialized", "session.started", "session.chunk", "session.message", "session.thought", "session.paused", "session.resumed", "session.checkpoint_created", "session.checkpoint_restored", "session.ended", "task.created", "task.scheduled", "task.dispatched", "task.status_changed", "task.started", "task.completed", "task.failed", "task.retry", "task.cancelled", "tool.requested", "tool.policy_checked", "tool.approval_required", "tool.approved", "tool.rejected", "tool.executed", "tool.failed", "policy.evaluated", "policy.allowed", "policy.blocked", "policy.violation", "governance.kill_switch_triggered", "verification.plan_created", "verification.started", "verification.assertion_passed", "verification.assertion_failed", "verification.completed", "evidence.collected", "evidence.sealed", "team.created", "team.member_joined", "team.member_left", "team.progress_updated", "team.delegation_started", "team.delegation_completed", "workspace.provisioned", "workspace.modified", "workspace.locked", "workspace.unlocked", "workspace.snapshot_created", "world.entity_mutated", "world.snapshot_captured", "simulation.started", "simulation.tick", "simulation.diff_generated", "simulation.completed", "audit.entry_recorded", "telemetry.metric_emitted", "system.heartbeat", "system.error"]>;
    tenantId: z.ZodString;
    agentId: z.ZodOptional<z.ZodString>;
    sessionId: z.ZodOptional<z.ZodString>;
    taskId: z.ZodOptional<z.ZodString>;
    workspaceId: z.ZodOptional<z.ZodString>;
    runtimeId: z.ZodOptional<z.ZodString>;
    timestamp: z.ZodDefault<z.ZodNumber>;
    isoTimestamp: z.ZodDefault<z.ZodString>;
    sequence: z.ZodNumber;
    source: z.ZodEnum<["engine.cline", "engine.adapter", "control.plane", "api", "verifier", "simulator", "scheduler", "policy.engine", "realtime.hub"]>;
    payload: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    traceId: z.ZodDefault<z.ZodString>;
    parentEventId: z.ZodOptional<z.ZodString>;
}, "eventId" | "timestamp" | "isoTimestamp" | "sequence" | "traceId"> & {
    eventId: z.ZodOptional<z.ZodString>;
    sequence: z.ZodOptional<z.ZodNumber>;
    traceId: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    tenantId: string;
    eventType: "agent.created" | "agent.updated" | "agent.deleted" | "agent.status_changed" | "agent.started" | "agent.paused" | "agent.resumed" | "agent.stopped" | "agent.aborted" | "agent.failed" | "session.initialized" | "session.started" | "session.chunk" | "session.message" | "session.thought" | "session.paused" | "session.resumed" | "session.checkpoint_created" | "session.checkpoint_restored" | "session.ended" | "task.created" | "task.scheduled" | "task.dispatched" | "task.status_changed" | "task.started" | "task.completed" | "task.failed" | "task.retry" | "task.cancelled" | "tool.requested" | "tool.policy_checked" | "tool.approval_required" | "tool.approved" | "tool.rejected" | "tool.executed" | "tool.failed" | "policy.evaluated" | "policy.allowed" | "policy.blocked" | "policy.violation" | "governance.kill_switch_triggered" | "verification.plan_created" | "verification.started" | "verification.assertion_passed" | "verification.assertion_failed" | "verification.completed" | "evidence.collected" | "evidence.sealed" | "team.created" | "team.member_joined" | "team.member_left" | "team.progress_updated" | "team.delegation_started" | "team.delegation_completed" | "workspace.provisioned" | "workspace.modified" | "workspace.locked" | "workspace.unlocked" | "workspace.snapshot_created" | "world.entity_mutated" | "world.snapshot_captured" | "simulation.started" | "simulation.tick" | "simulation.diff_generated" | "simulation.completed" | "audit.entry_recorded" | "telemetry.metric_emitted" | "system.heartbeat" | "system.error";
    source: "engine.cline" | "engine.adapter" | "control.plane" | "api" | "verifier" | "simulator" | "scheduler" | "policy.engine" | "realtime.hub";
    payload: Record<string, unknown>;
    runtimeId?: string | undefined;
    agentId?: string | undefined;
    taskId?: string | undefined;
    workspaceId?: string | undefined;
    eventId?: string | undefined;
    sessionId?: string | undefined;
    sequence?: number | undefined;
    traceId?: string | undefined;
    parentEventId?: string | undefined;
}, {
    tenantId: string;
    eventType: "agent.created" | "agent.updated" | "agent.deleted" | "agent.status_changed" | "agent.started" | "agent.paused" | "agent.resumed" | "agent.stopped" | "agent.aborted" | "agent.failed" | "session.initialized" | "session.started" | "session.chunk" | "session.message" | "session.thought" | "session.paused" | "session.resumed" | "session.checkpoint_created" | "session.checkpoint_restored" | "session.ended" | "task.created" | "task.scheduled" | "task.dispatched" | "task.status_changed" | "task.started" | "task.completed" | "task.failed" | "task.retry" | "task.cancelled" | "tool.requested" | "tool.policy_checked" | "tool.approval_required" | "tool.approved" | "tool.rejected" | "tool.executed" | "tool.failed" | "policy.evaluated" | "policy.allowed" | "policy.blocked" | "policy.violation" | "governance.kill_switch_triggered" | "verification.plan_created" | "verification.started" | "verification.assertion_passed" | "verification.assertion_failed" | "verification.completed" | "evidence.collected" | "evidence.sealed" | "team.created" | "team.member_joined" | "team.member_left" | "team.progress_updated" | "team.delegation_started" | "team.delegation_completed" | "workspace.provisioned" | "workspace.modified" | "workspace.locked" | "workspace.unlocked" | "workspace.snapshot_created" | "world.entity_mutated" | "world.snapshot_captured" | "simulation.started" | "simulation.tick" | "simulation.diff_generated" | "simulation.completed" | "audit.entry_recorded" | "telemetry.metric_emitted" | "system.heartbeat" | "system.error";
    source: "engine.cline" | "engine.adapter" | "control.plane" | "api" | "verifier" | "simulator" | "scheduler" | "policy.engine" | "realtime.hub";
    runtimeId?: string | undefined;
    agentId?: string | undefined;
    taskId?: string | undefined;
    workspaceId?: string | undefined;
    eventId?: string | undefined;
    sessionId?: string | undefined;
    sequence?: number | undefined;
    payload?: Record<string, unknown> | undefined;
    traceId?: string | undefined;
    parentEventId?: string | undefined;
}>;
export type CreateEventInput = z.infer<typeof CreateEventInputSchema>;
//# sourceMappingURL=events.d.ts.map