import { z } from "zod";
export declare const VerificationVerdictSchema: z.ZodEnum<["PASS", "FAIL", "INCONCLUSIVE", "SKIPPED"]>;
export type VerificationVerdict = z.infer<typeof VerificationVerdictSchema>;
export declare const AssertionTypeSchema: z.ZodEnum<["FILE_EXISTS", "FILE_CONTAINS", "FILE_EQUALS", "FILE_DOES_NOT_EXIST", "GIT_DIFF_EMPTY", "GIT_BRANCH_EXISTS", "GIT_COMMIT_PRESENT", "COMMAND_EXIT_ZERO", "COMMAND_OUTPUT_MATCHES", "TEST_SUITE_PASS", "BUILD_SUCCESS", "SECURITY_SCAN_CLEAN", "HTTP_STATUS_OK", "AGENT_EVALUATION"]>;
export type AssertionType = z.infer<typeof AssertionTypeSchema>;
export declare const VerificationAssertionSchema: z.ZodObject<{
    id: z.ZodString;
    type: z.ZodEnum<["FILE_EXISTS", "FILE_CONTAINS", "FILE_EQUALS", "FILE_DOES_NOT_EXIST", "GIT_DIFF_EMPTY", "GIT_BRANCH_EXISTS", "GIT_COMMIT_PRESENT", "COMMAND_EXIT_ZERO", "COMMAND_OUTPUT_MATCHES", "TEST_SUITE_PASS", "BUILD_SUCCESS", "SECURITY_SCAN_CLEAN", "HTTP_STATUS_OK", "AGENT_EVALUATION"]>;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    target: z.ZodString;
    expectedValue: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodNumber, z.ZodBoolean, z.ZodArray<z.ZodString, "many">, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
    timeoutSeconds: z.ZodDefault<z.ZodNumber>;
    critical: z.ZodDefault<z.ZodBoolean>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
    name: string;
    critical: boolean;
    id: string;
    metadata: Record<string, unknown>;
    timeoutSeconds: number;
    target: string;
    description?: string | undefined;
    expectedValue?: string | number | boolean | Record<string, unknown> | string[] | undefined;
}, {
    type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
    name: string;
    id: string;
    target: string;
    description?: string | undefined;
    critical?: boolean | undefined;
    metadata?: Record<string, unknown> | undefined;
    timeoutSeconds?: number | undefined;
    expectedValue?: string | number | boolean | Record<string, unknown> | string[] | undefined;
}>;
export type VerificationAssertion = z.infer<typeof VerificationAssertionSchema>;
export declare const AssertionResultSchema: z.ZodObject<{
    assertionId: z.ZodString;
    assertionName: z.ZodString;
    type: z.ZodEnum<["FILE_EXISTS", "FILE_CONTAINS", "FILE_EQUALS", "FILE_DOES_NOT_EXIST", "GIT_DIFF_EMPTY", "GIT_BRANCH_EXISTS", "GIT_COMMIT_PRESENT", "COMMAND_EXIT_ZERO", "COMMAND_OUTPUT_MATCHES", "TEST_SUITE_PASS", "BUILD_SUCCESS", "SECURITY_SCAN_CLEAN", "HTTP_STATUS_OK", "AGENT_EVALUATION"]>;
    verdict: z.ZodEnum<["PASS", "FAIL", "INCONCLUSIVE", "SKIPPED"]>;
    actualValue: z.ZodOptional<z.ZodUnknown>;
    errorMessage: z.ZodOptional<z.ZodString>;
    executionTimeMs: z.ZodDefault<z.ZodNumber>;
    stdout: z.ZodOptional<z.ZodString>;
    stderr: z.ZodOptional<z.ZodString>;
    evidenceId: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
    assertionId: string;
    assertionName: string;
    verdict: "PASS" | "FAIL" | "INCONCLUSIVE" | "SKIPPED";
    executionTimeMs: number;
    errorMessage?: string | undefined;
    evidenceId?: string | undefined;
    actualValue?: unknown;
    stdout?: string | undefined;
    stderr?: string | undefined;
}, {
    type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
    assertionId: string;
    assertionName: string;
    verdict: "PASS" | "FAIL" | "INCONCLUSIVE" | "SKIPPED";
    errorMessage?: string | undefined;
    evidenceId?: string | undefined;
    actualValue?: unknown;
    executionTimeMs?: number | undefined;
    stdout?: string | undefined;
    stderr?: string | undefined;
}>;
export type AssertionResult = z.infer<typeof AssertionResultSchema>;
export declare const VerificationPlanSchema: z.ZodObject<{
    id: z.ZodString;
    tenantId: z.ZodString;
    taskId: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    assertions: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<["FILE_EXISTS", "FILE_CONTAINS", "FILE_EQUALS", "FILE_DOES_NOT_EXIST", "GIT_DIFF_EMPTY", "GIT_BRANCH_EXISTS", "GIT_COMMIT_PRESENT", "COMMAND_EXIT_ZERO", "COMMAND_OUTPUT_MATCHES", "TEST_SUITE_PASS", "BUILD_SUCCESS", "SECURITY_SCAN_CLEAN", "HTTP_STATUS_OK", "AGENT_EVALUATION"]>;
        name: z.ZodString;
        description: z.ZodOptional<z.ZodString>;
        target: z.ZodString;
        expectedValue: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodNumber, z.ZodBoolean, z.ZodArray<z.ZodString, "many">, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
        timeoutSeconds: z.ZodDefault<z.ZodNumber>;
        critical: z.ZodDefault<z.ZodBoolean>;
        metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        name: string;
        critical: boolean;
        id: string;
        metadata: Record<string, unknown>;
        timeoutSeconds: number;
        target: string;
        description?: string | undefined;
        expectedValue?: string | number | boolean | Record<string, unknown> | string[] | undefined;
    }, {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        name: string;
        id: string;
        target: string;
        description?: string | undefined;
        critical?: boolean | undefined;
        metadata?: Record<string, unknown> | undefined;
        timeoutSeconds?: number | undefined;
        expectedValue?: string | number | boolean | Record<string, unknown> | string[] | undefined;
    }>, "many">>;
    requireVerifierAgent: z.ZodDefault<z.ZodBoolean>;
    verifierAgentPrompt: z.ZodOptional<z.ZodString>;
    maxExecutionTimeMs: z.ZodDefault<z.ZodNumber>;
    createdAt: z.ZodDefault<z.ZodString>;
    updatedAt: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    name: string;
    maxExecutionTimeMs: number;
    id: string;
    tenantId: string;
    createdAt: string;
    updatedAt: string;
    assertions: {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        name: string;
        critical: boolean;
        id: string;
        metadata: Record<string, unknown>;
        timeoutSeconds: number;
        target: string;
        description?: string | undefined;
        expectedValue?: string | number | boolean | Record<string, unknown> | string[] | undefined;
    }[];
    requireVerifierAgent: boolean;
    description?: string | undefined;
    taskId?: string | undefined;
    verifierAgentPrompt?: string | undefined;
}, {
    name: string;
    id: string;
    tenantId: string;
    description?: string | undefined;
    maxExecutionTimeMs?: number | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    taskId?: string | undefined;
    assertions?: {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        name: string;
        id: string;
        target: string;
        description?: string | undefined;
        critical?: boolean | undefined;
        metadata?: Record<string, unknown> | undefined;
        timeoutSeconds?: number | undefined;
        expectedValue?: string | number | boolean | Record<string, unknown> | string[] | undefined;
    }[] | undefined;
    requireVerifierAgent?: boolean | undefined;
    verifierAgentPrompt?: string | undefined;
}>;
export type VerificationPlan = z.infer<typeof VerificationPlanSchema>;
export declare const VerificationRunSchema: z.ZodObject<{
    id: z.ZodString;
    tenantId: z.ZodString;
    planId: z.ZodString;
    taskId: z.ZodOptional<z.ZodString>;
    sessionId: z.ZodOptional<z.ZodString>;
    workspaceId: z.ZodOptional<z.ZodString>;
    overallVerdict: z.ZodDefault<z.ZodEnum<["PASS", "FAIL", "INCONCLUSIVE", "SKIPPED"]>>;
    assertionResults: z.ZodDefault<z.ZodArray<z.ZodObject<{
        assertionId: z.ZodString;
        assertionName: z.ZodString;
        type: z.ZodEnum<["FILE_EXISTS", "FILE_CONTAINS", "FILE_EQUALS", "FILE_DOES_NOT_EXIST", "GIT_DIFF_EMPTY", "GIT_BRANCH_EXISTS", "GIT_COMMIT_PRESENT", "COMMAND_EXIT_ZERO", "COMMAND_OUTPUT_MATCHES", "TEST_SUITE_PASS", "BUILD_SUCCESS", "SECURITY_SCAN_CLEAN", "HTTP_STATUS_OK", "AGENT_EVALUATION"]>;
        verdict: z.ZodEnum<["PASS", "FAIL", "INCONCLUSIVE", "SKIPPED"]>;
        actualValue: z.ZodOptional<z.ZodUnknown>;
        errorMessage: z.ZodOptional<z.ZodString>;
        executionTimeMs: z.ZodDefault<z.ZodNumber>;
        stdout: z.ZodOptional<z.ZodString>;
        stderr: z.ZodOptional<z.ZodString>;
        evidenceId: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        assertionId: string;
        assertionName: string;
        verdict: "PASS" | "FAIL" | "INCONCLUSIVE" | "SKIPPED";
        executionTimeMs: number;
        errorMessage?: string | undefined;
        evidenceId?: string | undefined;
        actualValue?: unknown;
        stdout?: string | undefined;
        stderr?: string | undefined;
    }, {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        assertionId: string;
        assertionName: string;
        verdict: "PASS" | "FAIL" | "INCONCLUSIVE" | "SKIPPED";
        errorMessage?: string | undefined;
        evidenceId?: string | undefined;
        actualValue?: unknown;
        executionTimeMs?: number | undefined;
        stdout?: string | undefined;
        stderr?: string | undefined;
    }>, "many">>;
    summary: z.ZodOptional<z.ZodString>;
    evidenceChainRootHash: z.ZodOptional<z.ZodString>;
    startedAt: z.ZodDefault<z.ZodString>;
    completedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: string;
    tenantId: string;
    startedAt: string;
    planId: string;
    overallVerdict: "PASS" | "FAIL" | "INCONCLUSIVE" | "SKIPPED";
    assertionResults: {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        assertionId: string;
        assertionName: string;
        verdict: "PASS" | "FAIL" | "INCONCLUSIVE" | "SKIPPED";
        executionTimeMs: number;
        errorMessage?: string | undefined;
        evidenceId?: string | undefined;
        actualValue?: unknown;
        stdout?: string | undefined;
        stderr?: string | undefined;
    }[];
    taskId?: string | undefined;
    workspaceId?: string | undefined;
    summary?: string | undefined;
    completedAt?: string | undefined;
    sessionId?: string | undefined;
    evidenceChainRootHash?: string | undefined;
}, {
    id: string;
    tenantId: string;
    planId: string;
    taskId?: string | undefined;
    workspaceId?: string | undefined;
    startedAt?: string | undefined;
    summary?: string | undefined;
    completedAt?: string | undefined;
    sessionId?: string | undefined;
    overallVerdict?: "PASS" | "FAIL" | "INCONCLUSIVE" | "SKIPPED" | undefined;
    assertionResults?: {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        assertionId: string;
        assertionName: string;
        verdict: "PASS" | "FAIL" | "INCONCLUSIVE" | "SKIPPED";
        errorMessage?: string | undefined;
        evidenceId?: string | undefined;
        actualValue?: unknown;
        executionTimeMs?: number | undefined;
        stdout?: string | undefined;
        stderr?: string | undefined;
    }[] | undefined;
    evidenceChainRootHash?: string | undefined;
}>;
export type VerificationRun = z.infer<typeof VerificationRunSchema>;
export declare const CreateVerificationPlanRequestSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    tenantId: z.ZodString;
    taskId: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    assertions: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<["FILE_EXISTS", "FILE_CONTAINS", "FILE_EQUALS", "FILE_DOES_NOT_EXIST", "GIT_DIFF_EMPTY", "GIT_BRANCH_EXISTS", "GIT_COMMIT_PRESENT", "COMMAND_EXIT_ZERO", "COMMAND_OUTPUT_MATCHES", "TEST_SUITE_PASS", "BUILD_SUCCESS", "SECURITY_SCAN_CLEAN", "HTTP_STATUS_OK", "AGENT_EVALUATION"]>;
        name: z.ZodString;
        description: z.ZodOptional<z.ZodString>;
        target: z.ZodString;
        expectedValue: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodNumber, z.ZodBoolean, z.ZodArray<z.ZodString, "many">, z.ZodRecord<z.ZodString, z.ZodUnknown>]>>;
        timeoutSeconds: z.ZodDefault<z.ZodNumber>;
        critical: z.ZodDefault<z.ZodBoolean>;
        metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        name: string;
        critical: boolean;
        id: string;
        metadata: Record<string, unknown>;
        timeoutSeconds: number;
        target: string;
        description?: string | undefined;
        expectedValue?: string | number | boolean | Record<string, unknown> | string[] | undefined;
    }, {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        name: string;
        id: string;
        target: string;
        description?: string | undefined;
        critical?: boolean | undefined;
        metadata?: Record<string, unknown> | undefined;
        timeoutSeconds?: number | undefined;
        expectedValue?: string | number | boolean | Record<string, unknown> | string[] | undefined;
    }>, "many">>;
    requireVerifierAgent: z.ZodDefault<z.ZodBoolean>;
    verifierAgentPrompt: z.ZodOptional<z.ZodString>;
    maxExecutionTimeMs: z.ZodDefault<z.ZodNumber>;
    createdAt: z.ZodDefault<z.ZodString>;
    updatedAt: z.ZodDefault<z.ZodString>;
}, "id" | "createdAt" | "updatedAt">, "strip", z.ZodTypeAny, {
    name: string;
    maxExecutionTimeMs: number;
    tenantId: string;
    assertions: {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        name: string;
        critical: boolean;
        id: string;
        metadata: Record<string, unknown>;
        timeoutSeconds: number;
        target: string;
        description?: string | undefined;
        expectedValue?: string | number | boolean | Record<string, unknown> | string[] | undefined;
    }[];
    requireVerifierAgent: boolean;
    description?: string | undefined;
    taskId?: string | undefined;
    verifierAgentPrompt?: string | undefined;
}, {
    name: string;
    tenantId: string;
    description?: string | undefined;
    maxExecutionTimeMs?: number | undefined;
    taskId?: string | undefined;
    assertions?: {
        type: "FILE_EXISTS" | "FILE_CONTAINS" | "FILE_EQUALS" | "FILE_DOES_NOT_EXIST" | "GIT_DIFF_EMPTY" | "GIT_BRANCH_EXISTS" | "GIT_COMMIT_PRESENT" | "COMMAND_EXIT_ZERO" | "COMMAND_OUTPUT_MATCHES" | "TEST_SUITE_PASS" | "BUILD_SUCCESS" | "SECURITY_SCAN_CLEAN" | "HTTP_STATUS_OK" | "AGENT_EVALUATION";
        name: string;
        id: string;
        target: string;
        description?: string | undefined;
        critical?: boolean | undefined;
        metadata?: Record<string, unknown> | undefined;
        timeoutSeconds?: number | undefined;
        expectedValue?: string | number | boolean | Record<string, unknown> | string[] | undefined;
    }[] | undefined;
    requireVerifierAgent?: boolean | undefined;
    verifierAgentPrompt?: string | undefined;
}>;
export type CreateVerificationPlanRequest = z.infer<typeof CreateVerificationPlanRequestSchema>;
//# sourceMappingURL=verification.d.ts.map